steps:
 # build the container
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--network=cloudbuild','-t', 'gcr.io/cooknet-368603/server', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/cooknet-368603/server']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy', 'cooknet-368603-server', '--image', 'gcr.io/cooknet-368603/server', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/cooknet-368603/server'
